local addonName = ...
local SAdCore = LibStub("SAdCore-1")
local addon = SAdCore:GetAddon(addonName)

function addon:GetConfig()
    return {
        global = {
            textures = {
                ["aluminium"]      = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Aluminium",
                ["armory"]         = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Armory",
                ["bantobar"]       = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\BantoBar",
                ["bars"]           = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Bars",
                ["bezo"]           = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Bezo",
                ["bezo-dark1"]     = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Bezo-dark1",
                ["bezo-dark2"]     = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Bezo-dark2",
                ["blinkii"]        = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Blinkii",
                ["buionepixel"]    = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\BuiOnePixel",
                ["bumps"]          = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Bumps",
                ["button"]         = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Button",
                ["charcoal"]       = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Charcoal",
                ["cilo"]           = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Cilo",
                ["cloud"]          = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Cloud",
                ["combo"]          = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Combo",
                ["comet"]          = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Comet",
                ["dabs"]           = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Dabs",
                ["darkbottom"]     = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\DarkBottom",
                ["diagonal"]       = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Diagonal",
                ["empty"]          = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Empty",
                ["falumn"]         = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Falumn",
                ["fifths"]         = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Fifths",
                ["flat"]           = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Flat",
                ["fourths"]        = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Fourths",
                ["frost"]          = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Frost",
                ["glamour"]        = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Glamour",
                ["glass"]          = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Glass",
                ["glaze"]          = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Glaze",
                ["glaze2"]         = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Glaze2",
                ["gloss"]          = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Gloss",
                ["graphite"]       = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Graphite",
                ["grid"]           = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Grid",
                ["hatched"]        = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Hatched",
                ["healbot"]        = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Healbot",
                ["litestep"]       = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\LiteStep",
                ["litesteplite"]   = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\LiteStepLite",
                ["lyfe"]           = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Lyfe",
                ["melli"]          = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Melli",
                ["mellidark"]      = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\MelliDark",
                ["mellidarkrough"] = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\MelliDarkRough",
                ["minimalist"]     = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Minimalist",
                ["norm"]           = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Norm",
                ["otravi"]         = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Otravi",
                ["outline"]        = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Outline",
                ["perl"]           = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Perl",
                ["perl2"]          = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Perl2",
                ["pill"]           = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Pill",
                ["rain"]           = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Rain",
                ["rocks"]          = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Rocks",
                ["round"]          = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Round",
                ["ruben"]          = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Ruben",
                ["runes"]          = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Runes",
                ["skewed"]         = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Skewed",
                ["smooth"]         = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Smooth",
                ["smoothv2"]       = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Smoothv2",
                ["smudge"]         = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Smudge",
                ["steel"]          = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Steel",
                ["striped"]        = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Striped",
                ["toxiui-clean"]   = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\ToxiUI-clean",
                ["toxiui-dark"]    = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\ToxiUI-dark",
                ["toxiui-g1"]      = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\ToxiUI-g1",
                ["toxiui-g2"]      = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\ToxiUI-g2",
                ["toxiui-grad"]    = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\ToxiUI-grad",
                ["toxiui-half"]    = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\ToxiUI-half",
                ["tube"]           = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Tube",
                ["water"]          = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Water",
                ["wglass"]         = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Wglass",
                ["wisps"]          = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Wisps",
                ["xeon"]           = "Interface\\AddOns\\" .. addonName .. "\\Media\\Statusbar\\Xeon",
            },

            font = "DorisPP",
            
            refreshDelay = 0.1,

            manaColor = "2482ff",
            rageColor = "ff0000",
            focusColor = "ff8000",
            energyColor = "ffff00",
            runicPowerColor = "00d4ff",
            lunarPowerColor = "4d85e6",
            comboPointColor = "ffaa00",
            runesColor = "00d4ff",

            hostileColor = "ff0000",
            neutralColor = "ffff00",
            friendlyColor = "00ff00",

            highlightColor = "ffbb00",

            castbarColor = "ffbb00",
            castbarChannelColor = "ffbb00",
            castbarNonInterruptibleColor = "888888",
            castbarEmpowerColor = "5588dd",

            dispelColors = {
                Magic   = "ff00ffFF",
                Curse   = "990099ff",
                Disease = "bbcc00FF",
                Poison  = "00cc00FF",
                Bleed   = "CC0000FF",
                Enrage  = "FF3300FF",
                default = "FFFFFFFF",
            },

            roleIcons = {
                TANK = "RaidFrame-Icon-MainTank",
                HEALER = "icons_64x64_heal",
                DAMAGER = "RaidFrame-Icon-MainAssist",
            },

            specAbbrevById = {
                -- Warrior
                [71] = "ARMS",
                [72] = "FURY",
                [73] = "PROT",
                -- Paladin
                [65] = "HOLY",
                [66] = "PROT",
                [70] = "RET",
                -- Hunter
                [253] = "BM",
                [254] = "MM",
                [255] = "SV",
                -- Rogue
                [259] = "ASSA",
                [260] = "OUTL",
                [261] = "SUB",
                -- Priest
                [256] = "DISC",
                [257] = "HOLY",
                [258] = "SPRIEST",
                -- Death Knight
                [250] = "BDK",
                [251] = "FDK",
                [252] = "UDK",
                -- Shaman
                [262] = "ELE",
                [263] = "ENH",
                [264] = "RESTO",
                -- Mage
                [62] = "ARC",
                [63] = "FIRE",
                [64] = "FROST",
                -- Warlock
                [265] = "AFF",
                [266] = "DEMO",
                [267] = "DESTRO",
                -- Monk
                [268] = "BREW",
                [269] = "WW",
                [270] = "MW",
                -- Druid
                [102] = "BAL",
                [103] = "FERAL",
                [104] = "GUARD",
                [105] = "RESTO",
                -- Demon Hunter
                [577] = "HAVOC",
                [581] = "VENG",
                -- Evoker
                [1467] = "DEV",
                [1468] = "PRES",
                [1473] = "AUG",
            },
        },
        player = {
            enabled = self:GetValue("player", "enabled"),
            hideBlizzard = true,
            hideBlizzardBuffs = true,
            hideBlizzardDebuffs = true,
            frameName = "frmdPlayerFrame",
            anchor = "TOPRIGHT",
            relativeTo = "MainActionBar",
            relativePoint = "TOPLEFT",
            offsetX = -10,
            offsetY = 0,
            width = 203,
            height = 41,
            backgroundColor = "00000088",
            borderWidth = 2,
            borderColor = "000000FF",

            modules = {
                health = {
                    enabled = true,
                    frameName = "frmdPlayerHealthbar",
                    anchor = "TOP",
                    relativeTo = "frmdPlayerFrame",
                    relativePoint = "TOP",
                    texture = "smooth",
                    height = 41,
                    offsetX = 0,
                    offsetY = 0,
                    color = "class",
                },
                text = {
                    {
                        enabled = true,
                        anchor = "BOTTOMLEFT",
                        relativeTo = "frmdPlayerFrame",
                        relativePoint = "TOPLEFT",
                        offsetX = 0,
                        offsetY = -7,
                        size = 14,
                        color = "FFFFFF",
                        format = "[name:medium]",
                    },
                    {
                        enabled = true,
                        anchor = "BOTTOMRIGHT",
                        relativeTo = "frmdPlayerFrame",
                        relativePoint = "TOPRIGHT",
                        offsetX = 0,
                        offsetY = -6,
                        size = 14,
                        color = "FFFFFF",
                        format = "[perhp]% / [maxhp:short]",
                    },
                },
                power = {
                    enabled = true,
                    frameName = "frmdPlayerPowerbar",
                    anchor = "BOTTOM",
                    relativeTo = "frmdPlayerFrame",
                    relativePoint = "BOTTOM",
                    texture = "minimalist",
                    height = 12,
                    adjustHealthbarHeight = true,
                    offsetX = 0,
                    offsetY = 0,
                    borderWidth = 1,
                    borderColor = "000000FF",
                },
                castbar = {
                    enabled = true,
                    frameName = "frmdPlayerCastbar",
                    anchor = "BOTTOM",
                    relativeTo = "MainActionBar",
                    relativePoint = "TOP",
                    width = 332,
                    height = 30,
                    offsetX = 0,
                    offsetY = 10,
                    texture = "smooth",
                    showSpellName = true,
                    textAlignment = "CENTER",
                    showIcon = false,
                    iconPosition = "LEFT",
                    showCastTime = false,
                    backgroundColor = "00000088",
                    borderWidth = 2,
                    borderColor = "000000FF",
                },
                auraFilters = {
                    {
                        name = "StaticPlayerBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        excludeSubFilters = {"CANCELABLE"},
                        disableMouse = false,
                        frameName = "frmdStaticPlayerBuffs",
                        anchor = "TOPRIGHT",
                        relativeTo = "UIParent",
                        relativePoint = "TOP",
                        offsetX = -100,
                        offsetY = 0,
                        iconSize = 20,
                        spacingX = 2,
                        spacingY = 2,
                        maxIcons = 21,
                        perRow = 21,
                        growthX = "LEFT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                    },
                    {
                        name = "ActivePlayerBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"CANCELABLE"},
                        disableMouse = false,
                        frameName = "frmdActivePlayerBuffs",
                        anchor = "TOPRIGHT",
                        relativeTo = "frmdStaticPlayerBuffs",
                        relativePoint = "BOTTOMRIGHT",
                        offsetX = 0,
                        offsetY = -10,
                        iconSize = 30,
                        spacingX = 2,
                        spacingY = 2,
                        maxIcons = 30,
                        perRow = 15,
                        growthX = "LEFT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                    },
                    {
                        name = "ActivePlayerDebuffs",
                        enabled = true,
                        baseFilter = "HARMFUL",
                        disableMouse = false,
                        frameName = "frmdActivePlayerDebuffs",
                        anchor = "TOPRIGHT",
                        relativeTo = "frmdActivePlayerBuffs",
                        relativePoint = "BOTTOMRIGHT",
                        offsetX = 0,
                        offsetY = -10,
                        iconSize = 42,
                        spacingX = 2,
                        spacingY = 2,
                        maxIcons = 11,
                        perRow = 11,
                        growthX = "LEFT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "FF0000FF",
                    },
                },
                absorbs = {
                    enabled = true,
                    opacity = .5,
                    maxAbsorbOverflow = 1.0,
                    texture = "Diagonal",
                },
                combatIndicator = {
                    enabled = true,
                    atlasTexture = "titleprestige-prestigeicon",
                    size = 30,
                    strata = "LOW",
                    anchor = "CENTER",
                    relativeTo = "MainActionBar",
                    relativePoint = "CENTER",
                    offsetX = 0,
                    offsetY = 44,
                },
                restingIndicator = {
                    enabled = true,
                    atlasTexture = "plunderstorm-nameplates-icon-2",
                    size = 36,
                    strata = "LOW",
                    anchor = "CENTER",
                    relativeTo = "MainActionBar",
                    relativePoint = "CENTER",
                    offsetX = 0,
                    offsetY = 44,
                },
            },
        },
        target = {
            enabled = self:GetValue("target", "enabled"),
            hideBlizzard = true,
            frameName = "frmdTargetFrame",
            anchor = "TOPLEFT",
            relativeTo = "MainActionBar",
            relativePoint = "TOPRIGHT",
            offsetX = 10,
            offsetY = 0,
            width = 203,
            height = 41,
            backgroundColor = "00000088",
            borderWidth = 2,
            borderColor = "000000FF",
            modules = {
                health = {
                    enabled = true,
                    frameName = "frmdTargetHealth",
                    anchor = "TOP",
                    relativeTo = "frmdTargetFrame",
                    relativePoint = "TOP",
                    texture = "smooth",
                    height = 41,
                    offsetX = 0,
                    offsetY = 0,
                    color = "class",
                },
                text = {
                    {
                        enabled = true,
                        anchor = "BOTTOMLEFT",
                        relativeTo = "frmdTargetFrame",
                        relativePoint = "TOPLEFT",
                        offsetX = 0,
                        offsetY = -7,
                        size = 14,
                        color = "FFFFFF",
                        format = "[name:medium]",
                    },
                    {
                        enabled = true,
                        anchor = "BOTTOMRIGHT",
                        relativeTo = "frmdTargetFrame",
                        relativePoint = "TOPRIGHT",
                        offsetX = 0,
                        offsetY = -6,
                        size = 14,
                        color = "FFFFFF",
                        format = "[perhp]% / [maxhp:short]",
                    },
                },
                power = {
                    enabled = true,
                    frameName = "frmdTargetPowerbar",
                    anchor = "BOTTOM",
                    relativeTo = "frmdTargetFrame",
                    relativePoint = "BOTTOM",
                    texture = "minimalist",
                    height = 12,
                    adjustHealthbarHeight = true,
                    offsetX = 0,
                    offsetY = 0,
                    borderWidth = 1,
                    borderColor = "000000FF",
                },
                castbar = {
                    enabled = true,
                    frameName = "frmdTargetCastbar",
                    anchor = "TOP",
                    relativeTo = "frmdTargetFrame",
                    relativePoint = "BOTTOM",
                    height = 20,
                    offsetX = 0,
                    offsetY = 0,
                    texture = "smooth",
                    showSpellName = true,
                    textAlignment = "LEFT",
                    showIcon = false,
                    iconPosition = "RIGHT",
                    showCastTime = false,
                    backgroundColor = "00000088",
                    borderWidth = 2,
                    borderColor = "000000FF",
                },
                auraFilters = {
                    {
                        name = "StaticTargetBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        excludeSubFilters = {"CANCELABLE"},
                        disableMouse = false,
                        frameName = "frmdStaticTargetBuffs",
                        anchor = "TOPLEFT",
                        relativeTo = "UIParent",
                        relativePoint = "TOP",
                        offsetX = 100,
                        offsetY = 0,
                        iconSize = 20,
                        spacingX = 2,
                        spacingY = 2,
                        maxIcons = 21,
                        perRow = 21,
                        growthX = "RIGHT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                    },
                    {
                        name = "ActiveTargetBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"CANCELABLE"},
                        disableMouse = false,
                        frameName = "frmdActiveTargetBuffs",
                        anchor = "TOPLEFT",
                        relativeTo = "frmdStaticTargetBuffs",
                        relativePoint = "BOTTOMLEFT",
                        offsetX = 0,
                        offsetY = -10,
                        iconSize = 30,
                        spacingX = 2,
                        spacingY = 2,
                        maxIcons = 30,
                        perRow = 15,
                        growthX = "RIGHT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                    },
                    {
                        name = "ActiveTargetDebuffs",
                        enabled = true,
                        baseFilter = "HARMFUL",
                        disableMouse = false,
                        frameName = "frmdActiveTargetDebuffs",
                        anchor = "TOPLEFT",
                        relativeTo = "frmdActiveTargetBuffs",
                        relativePoint = "BOTTOMLEFT",
                        offsetX = 0,
                        offsetY = -10,
                        iconSize = 42,
                        spacingX = 2,
                        spacingY = 2,
                        maxIcons = 11,
                        perRow = 11,
                        growthX = "RIGHT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "FF0000FF",
                    },
                },
                absorbs = {
                    enabled = true,
                    opacity = .5,
                    maxAbsorbOverflow = 1.0,
                    texture = "Diagonal",
                },
            },
        },
        targetTarget = {
            enabled = self:GetValue("targetTarget", "enabled"),
            hideBlizzard = true,
            frameName = "frmdTargetTargetFrame",
            anchor = "TOPLEFT",
            relativeTo = "frmdTargetFrame",
            relativePoint = "TOPRIGHT",
            offsetX = 10,
            offsetY = 0,
            width = 93,
            height = 21,
            backgroundColor = "00000088",
            borderWidth = 2,
            borderColor = "000000FF",
            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    texture = "smooth",
                },
                text = {
                    {
                        enabled = true,
                        anchor = "LEFT",
                        relativeTo = "frmdTargetTargetFrame",
                        relativePoint = "LEFT",
                        offsetX = 3,
                        offsetY = 0,
                        size = 11,
                        color = "FFFFFF",
                        format = "[name:short]",
                    },
                },
            },
        },
        targetTargetTarget = {
            enabled = self:GetValue("targetTargetTarget", "enabled"),
            hideBlizzard = true,
            frameName = "frmdTargetTargetTargetFrame",
            anchor = "TOPRIGHT",
            relativeTo = "frmdTargetTargetFrame",
            relativePoint = "BOTTOMRIGHT",
            offsetX = 0,
            offsetY = 0,
            width = 75,
            height = 20,
            backgroundColor = "00000088",
            borderWidth = 2,
            borderColor = "000000FF",
            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    texture = "smooth",
                },
                text = {
                    {
                        enabled = true,
                        anchor = "LEFT",
                        relativeTo = "frmdTargetTargetTargetFrame",
                        relativePoint = "LEFT",
                        offsetX = 3,
                        offsetY = 0,
                        size = 11,
                        color = "FFFFFF",
                        format = "[name:short]",
                    },
                },
            },
        },
        focus = {
            enabled = self:GetValue("focus", "enabled"),
            hideBlizzard = true,
            frameName = "frmdFocusFrame",
            anchor = "TOPRIGHT",
            relativeTo = "frmdPlayerFrame",
            relativePoint = "TOPLEFT",
            offsetX = -10,
            offsetY = 0,
            width = 93,
            height = 21,
            backgroundColor = "00000088",
            borderWidth = 2,
            borderColor = "000000FF",
            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    texture = "smooth",
                },
                text = {
                    {
                        enabled = true,
                        anchor = "LEFT",
                        relativeTo = "frmdFocusFrame",
                        relativePoint = "LEFT",
                        offsetX = 3,
                        offsetY = 0,
                        size = 11,
                        color = "FFFFFF",
                        format = "[name:short]",
                    },
                },
            },
        },
        focusTarget = {
            enabled = self:GetValue("focusTarget", "enabled"),
            hideBlizzard = true,
            frameName = "frmdFocusTargetFrame",
            anchor = "TOPLEFT",
            relativeTo = "frmdFocusFrame",
            relativePoint = "BOTTOMLEFT",
            offsetX = 0,
            offsetY = 0,
            width = 75,
            height = 20,
            backgroundColor = "00000088",
            borderWidth = 2,
            borderColor = "000000FF",
            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    texture = "smooth",
                },
                text = {
                    {
                        enabled = true,
                        anchor = "LEFT",
                        relativeTo = "frmdFocusTargetFrame",
                        relativePoint = "LEFT",
                        offsetX = 3,
                        offsetY = 0,
                        size = 11,
                        color = "FFFFFF",
                        format = "[name:short]",
                    },
                },
            },
        },
        pet = {
            enabled = self:GetValue("pet", "enabled"),
            hideBlizzard = true,
            frameName = "frmdPetFrame",
            anchor = "TOPLEFT",
            relativeTo = "PlayerFrame",
            relativePoint = "TOPRIGHT",
            offsetX = 10,
            offsetY = 200,
            width = 93,
            height = 29,
            borderWidth = 2,
            borderColor = "000000FF",
            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    texture = "smooth",
                },
                text = {
                    {
                        enabled = true,
                        anchor = "CENTER",
                        relativeTo = "frmdPetFrame",
                        relativePoint = "CENTER",
                        offsetX = 3,
                        offsetY = 0,
                        size = 11,
                        color = "FFFFFF",
                        format = "[name:short]",
                    },
                },
            },
        },
        party = {
            enabled = self:GetValue("party", "enabled"),
            hideBlizzard = true,

            -- Container
            frameName = "frmdPartyContainer",
            anchor = "RIGHT",
            relativeTo = "UIParent",
            relativePoint = "CENTER",
            offsetX = -300,
            offsetY = 0,
            containerBackgroundColor = "00000000",
            containerBorderWidth = 0,
            containerBorderColor = "00000000",

            -- Unit layout
            maxUnits = 5,
            perRow = 1,
            spacingX = 0,
            spacingY = -1,
            growthX = "RIGHT",
            growthY = "DOWN",

            -- Individual unit frame settings
            unitWidth = 150,
            unitHeight = 60,
            unitBackgroundColor = "00000088",
            unitBorderWidth = 2,
            unitBorderColor = "000000FF",
            highlightSelected = true,

            -- Modules (applied to each unit frame)
            modules = {
                health = {
                    enabled = true,
                    color = "class",
                    texture = "smooth",
                },
                text = {
                    {
                        enabled = true,
                        anchor = "TOPLEFT",
                        relativePoint = "TOPLEFT",
                        offsetX = 14,
                        offsetY = -6,
                        size = 11,
                        color = "FFFFFF",
                        format = "[name:short]",
                    },
                    {
                        enabled = true,
                        anchor = "TOPRIGHT",
                        relativePoint = "TOPRIGHT",
                        offsetX = 0,
                        offsetY = -6,
                        size = 11,
                        color = "FFFFFF",
                        format = "[spec]",
                    },
                },
                power = {
                    enabled = true,
                    anchor = "BOTTOM",
                    relativePoint = "BOTTOM",
                    texture = "minimalist",
                    height = 12,
                    adjustHealthbarHeight = true,
                    onlyHealer = true,
                    offsetX = 0,
                    offsetY = 0,
                    borderWidth = 1,
                    borderColor = "000000FF",
                },
                roleIcon = {
                    enabled = true,
                    size = 12,
                    desaturate = true,
                    color = "FFFFFF",
                    anchor = "TOPLEFT",
                    relativePoint = "TOPLEFT",
                    offsetX = 1,
                    offsetY = -5,
                    defaultIcon = "common-button-square-gray-up",
                    defaultAlpha = 0.5,
                },
                dispelHighlight = {
                    enabled = true,
                    borderWidth = 4,
                },
                trinket = {
                    enabled = true,
                    iconSize = 36,
                    iconBorderWidth = 1,
                    iconBorderColor = "000000FF",
                    anchor = "TOPRIGHT",
                    relativePoint = "TOPLEFT",
                    offsetX = -6,
                    offsetY = 0,
                    showSwipe = true,
                    showCooldownNumbers = true,
                    cooldownDesaturate = true,
                    cooldownAlpha = 0.5,
                },
                castbar = {
                    enabled = true,
                    anchor = "BOTTOMLEFT",
                    relativePoint = "BOTTOMRIGHT",
                    width = 124,
                    height = 18,
                    offsetX = 9,
                    offsetY = 0,
                    texture = "smooth",
                    showSpellName = true,
                    textSize = 9,
                    textPadding = 0,
                    textAlignment = "LEFT",
                    showIcon = false,
                    showCastTime = false,
                    backgroundColor = "00000088",
                    borderWidth = 1,
                    borderColor = "000000FF",
                },
                auraFilters = {
                    {
                        name = "PartyPlayerBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"RAID_IN_COMBAT"},
                        excludeSubFilters = {"NOT_CANCELABLE"},
                        disableMouse = true,
                        relativeToModule = "Health",
                        anchor = "BOTTOMRIGHT",
                        relativePoint = "BOTTOMRIGHT",
                        offsetX = 0,
                        offsetY = 2,
                        iconSize = 20,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 6,
                        perRow = 6,
                        growthX = "LEFT",
                        growthY = "UP",
                        showSwipe = true,
                        showCooldownNumbers = false,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                    },
                    {
                        name = "PartyDebuffs",
                        enabled = true,
                        baseFilter = "HARMFUL",
                        disableMouse = true,
                        anchor = "BOTTOMRIGHT",
                        relativePoint = "BOTTOMLEFT",
                        offsetX = -6,
                        offsetY = 0,
                        iconSize = 20,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 6,
                        perRow = 6,
                        growthX = "LEFT",
                        growthY = "UP",
                        showSwipe = true,
                        showCooldownNumbers = false,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                    },
                    {
                        name = "PartyCrowdControl",
                        enabled = true,
                        baseFilter = "HARMFUL",
                        subFilters = {"CROWD_CONTROL"},
                        disableMouse = true,
                        anchor = "TOPLEFT",
                        relativePoint = "TOPRIGHT",
                        offsetX = 6,
                        offsetY = 0,
                        iconSize = 36,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 1,
                        perRow = 1,
                        growthX = "RIGHT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                        showGlow = true,
                        glowColor = "FF0000",
                        placeholderIcon = "spell_shaman_hex",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88"
                    },
                    {
                        name = "PartyDefensives",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"BIG_DEFENSIVE", "EXTERNAL_DEFENSIVE"},
                        disableMouse = true,
                        relativeToModule = "PartyCrowdControl",
                        anchor = "TOPLEFT",
                        relativePoint = "TOPRIGHT",
                        offsetX = 2,
                        offsetY = 0,
                        iconSize = 36,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 1,
                        perRow = 1,
                        growthX = "RIGHT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                        showGlow = true,
                        glowColor = "00ff98",
                        placeholderIcon = "inv_shield_04",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88"
                    },
                    {
                        name = "PartyImportantBuffs",
                        enabled = true,
                        baseFilter = "HELPFUL",
                        subFilters = {"IMPORTANT"},
                        disableMouse = true,
                        relativeToModule = {"PartyDefensives", "PartyCrowdControl"},
                        anchor = "TOPLEFT",
                        relativePoint = "TOPRIGHT",
                        offsetX = 2,
                        offsetY = 0,
                        iconSize = 36,
                        spacingX = 2,
                        spacingY = 0,
                        maxIcons = 1,
                        perRow = 1,
                        growthX = "RIGHT",
                        growthY = "DOWN",
                        showSwipe = true,
                        showCooldownNumbers = true,
                        tooltipAnchor = "ANCHOR_BOTTOMLEFT",
                        containerBackgroundColor = "00000000",
                        containerBorderWidth = 0,
                        containerBorderColor = "00000000",
                        iconBorderWidth = 1,
                        iconBorderColor = "000000FF",
                        showGlow = true,
                        glowColor = "11aaee",
                        placeholderIcon = "spell_holy_avenginewrath",
                        placeholderDesaturate = true,
                        placeholderColor = "FFFFFF88"
                    },
                },
                targetedBy = {
                    enabled = true,
                    size = 36,
                    relativeToModule = {"PartyImportantBuffs", "PartyDefensives", "PartyCrowdControl"},
                    anchor = "TOPLEFT",
                    relativePoint = "TOPRIGHT",
                    offsetX = 2,
                    offsetY = 0,
                    backgroundColor = "00000088",
                    borderWidth = 1,
                    borderColor = "000000FF",
                    textColor = "FFFFFFFF",
                    inactiveTextColor = "33333388",
                    textSize = 18,
                },
            },
        },
        arena = {
            enabled = self:GetValue("arena", "enabled"),
        },
    }
end
